2025-01-28 16:25:31,951 - ERROR - HTTP error for https://9to5linux.com/: 403 Client Error: Forbidden for url: https://9to5linux.com/
2025-01-28 16:25:36,772 - ERROR - HTTP error for https://distrowatch.com/: 403 Client Error: Forbidden for url: https://distrowatch.com/
2025-01-28 16:25:38,116 - ERROR - HTTP error for https://fabiensanglard.net/: 406 Client Error: Not Acceptable for url: https://fabiensanglard.net/
2025-01-28 16:25:40,415 - ERROR - HTTP error for https://machinelearningmastery.com/blog/: 403 Client Error: Forbidden for url: https://machinelearningmastery.com/blog/
2025-01-28 16:25:41,803 - ERROR - HTTP error for https://news.mit.edu/topic/artificial-intelligence: 404 Client Error: Not Found for url: https://news.mit.edu/topic/artificial-intelligence
2025-01-28 16:25:41,876 - ERROR - HTTP error for https://openai.com/blog/: 403 Client Error: Forbidden for url: https://openai.com/blog/
2025-01-28 16:25:45,027 - ERROR - HTTP error for https://www.aniakubow.com/: HTTPSConnectionPool(host='www.aniakubow.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002050B7B48D0>: Failed to resolve 'www.aniakubow.com' ([Errno 11001] getaddrinfo failed)"))
2025-01-28 16:25:46,440 - ERROR - HTTP error for https://www.eleuther.ai/news/: 404 Client Error: Not Found for url: https://www.eleuther.ai/news/
2025-01-28 16:25:48,563 - ERROR - HTTP error for https://www.howtoforge.com/: 403 Client Error: Forbidden for url: https://www.howtoforge.com/
2025-01-28 16:25:48,635 - ERROR - HTTP error for https://www.kdnuggets.com/: 403 Client Error: Forbidden for url: https://www.kdnuggets.com/
2025-01-28 16:25:48,822 - ERROR - HTTP error for https://www.lauramedalia.com/: HTTPSConnectionPool(host='www.lauramedalia.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002050BDA8610>: Failed to resolve 'www.lauramedalia.com' ([Errno 11002] getaddrinfo failed)"))
2025-01-28 17:09:30,681 - ERROR - HTTP error for https://ai.facebook.com/blog/: 400 Client Error: Bad Request for url: https://ai.facebook.com/blog/
2025-01-28 17:09:39,245 - ERROR - HTTP error for https://distrowatch.com/: HTTPSConnectionPool(host='distrowatch.com', port=443): Max retries exceeded with url: / (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:09:50,103 - ERROR - HTTP error for https://machinelearningmastery.com/blog/: HTTPSConnectionPool(host='machinelearningmastery.com', port=443): Max retries exceeded with url: /blog/ (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:09:51,693 - ERROR - HTTP error for https://news.mit.edu/topic/artificial-intelligence: 404 Client Error: Not Found for url: https://news.mit.edu/topic/artificial-intelligence
2025-01-28 17:09:57,992 - ERROR - HTTP error for https://openai.com/blog/: HTTPSConnectionPool(host='openai.com', port=443): Max retries exceeded with url: /blog/ (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:10:07,150 - ERROR - HTTP error for https://www.aniakubow.com/: HTTPSConnectionPool(host='www.aniakubow.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F5738B7B90>: Failed to resolve 'www.aniakubow.com' ([Errno 11001] getaddrinfo failed)"))
2025-01-28 17:10:08,663 - ERROR - HTTP error for https://www.eleuther.ai/news/: 404 Client Error: Not Found for url: https://www.eleuther.ai/news/
2025-01-28 17:10:17,168 - ERROR - HTTP error for https://www.howtoforge.com/: HTTPSConnectionPool(host='www.howtoforge.com', port=443): Max retries exceeded with url: / (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:10:23,452 - ERROR - HTTP error for https://www.kdnuggets.com/: HTTPSConnectionPool(host='www.kdnuggets.com', port=443): Max retries exceeded with url: / (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:10:29,553 - ERROR - HTTP error for https://www.lauramedalia.com/: HTTPSConnectionPool(host='www.lauramedalia.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F572C869D0>: Failed to resolve 'www.lauramedalia.com' ([Errno 11002] getaddrinfo failed)"))
2025-01-28 17:10:40,088 - ERROR - HTTP error for https://www.marktechpost.com/: HTTPSConnectionPool(host='www.marktechpost.com', port=443): Max retries exceeded with url: / (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
2025-01-28 17:41:40,782 - ERROR - HTTP error for https://ai.meta.com/blog/: 400 Client Error: Bad Request for url: https://ai.meta.com/blog/
2025-01-28 17:41:48,730 - ERROR - HTTP error for https://distrowatch.com/: HTTPSConnectionPool(host='distrowatch.com', port=443): Max retries exceeded with url: / (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:41:59,671 - ERROR - HTTP error for https://machinelearningmastery.com/blog/: HTTPSConnectionPool(host='machinelearningmastery.com', port=443): Max retries exceeded with url: /blog/ (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:42:00,984 - ERROR - HTTP error for https://news.mit.edu/topic/artificial-intelligence: 404 Client Error: Not Found for url: https://news.mit.edu/topic/artificial-intelligence
2025-01-28 17:42:07,243 - ERROR - HTTP error for https://openai.com/blog/: HTTPSConnectionPool(host='openai.com', port=443): Max retries exceeded with url: /blog/ (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:42:15,261 - ERROR - HTTP error for https://www.eleuther.ai/news/: 404 Client Error: Not Found for url: https://www.eleuther.ai/news/
2025-01-28 17:42:23,704 - ERROR - HTTP error for https://www.howtoforge.com/: HTTPSConnectionPool(host='www.howtoforge.com', port=443): Max retries exceeded with url: / (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:42:31,989 - ERROR - HTTP error for https://www.kdnuggets.com/: HTTPSConnectionPool(host='www.kdnuggets.com', port=443): Max retries exceeded with url: / (Caused by ResponseError('too many 403 error responses'))
2025-01-28 17:42:44,833 - ERROR - HTTP error for https://www.marktechpost.com/category/technology/ai-shorts/: HTTPSConnectionPool(host='www.marktechpost.com', port=443): Max retries exceeded with url: /category/technology/ai-shorts/ (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
2025-01-28 18:05:26,711 - ERROR - HTTP error for https://9to5linux.com/: HTTPSConnectionPool(host='9to5linux.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B26AEB7750>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')))
2025-01-28 18:06:36,731 - ERROR - HTTP error for https://addyosmani.com/: HTTPSConnectionPool(host='addyosmani.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B26AEB4990>, 'Connection to 123.123.123.123 timed out. (connect timeout=15)')))
2025-01-28 18:07:45,770 - ERROR - HTTP error for https://ai.googleblog.com/: HTTPSConnectionPool(host='ai.googleblog.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B26AEBA810>, 'Connection to 123.123.123.123 timed out. (connect timeout=15)')))
2025-01-28 18:08:55,819 - ERROR - HTTP error for https://ai.meta.com/blog/: HTTPSConnectionPool(host='ai.meta.com', port=443): Max retries exceeded with url: /blog/ (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B26AEC6F50>, 'Connection to 123.123.123.123 timed out. (connect timeout=15)')))
2025-01-28 18:10:03,834 - ERROR - HTTP error for https://benawad.com/: HTTPSConnectionPool(host='benawad.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B26AEC06D0>, 'Connection to 123.123.123.123 timed out. (connect timeout=15)')))
2025-01-28 18:10:11,919 - ERROR - HTTP error for https://blog.paperspace.com/: HTTPSConnectionPool(host='blog.paperspace.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B26AEC5E50>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')))
2025-01-28 18:10:20,927 - ERROR - HTTP error for https://blog.pragmaticengineer.com/: HTTPSConnectionPool(host='blog.pragmaticengineer.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B26AEAC110>: Failed to resolve '345.345.345.345' ([Errno 11001] getaddrinfo failed)")))
2025-01-28 18:11:31,971 - ERROR - HTTP error for https://blog.tensorflow.org/: HTTPSConnectionPool(host='blog.tensorflow.org', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B26AEB6D50>, 'Connection to 123.123.123.123 timed out. (connect timeout=15)')))
2025-01-28 18:12:42,021 - ERROR - HTTP error for https://cassidoo.co/: HTTPSConnectionPool(host='cassidoo.co', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B26AEC1C10>, 'Connection to 123.123.123.123 timed out. (connect timeout=15)')))
2025-01-28 18:13:52,056 - ERROR - HTTP error for https://codewithmosh.com/: HTTPSConnectionPool(host='codewithmosh.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B26AF31190>, 'Connection to 123.123.123.123 timed out. (connect timeout=15)')))
2025-01-28 18:14:01,106 - ERROR - HTTP error for https://distill.pub/: HTTPSConnectionPool(host='distill.pub', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B26AEB6650>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')))
2025-01-28 18:14:11,120 - ERROR - HTTP error for https://distrowatch.com/: HTTPSConnectionPool(host='distrowatch.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B26AEC5C10>: Failed to resolve '456.456.456.456' ([Errno 11001] getaddrinfo failed)")))
2025-01-28 18:19:42,373 - ERROR - HTTP error for https://ai.meta.com/blog/: 400 Client Error: Bad Request for url: https://ai.meta.com/blog/
2025-01-28 18:20:20,466 - ERROR - HTTP error for https://distrowatch.com/: HTTPSConnectionPool(host='distrowatch.com', port=443): Max retries exceeded with url: / (Caused by ResponseError('too many 403 error responses'))
2025-01-28 18:21:03,768 - ERROR - HTTP error for https://machinelearningmastery.com/blog/: HTTPSConnectionPool(host='machinelearningmastery.com', port=443): Max retries exceeded with url: /blog/ (Caused by ResponseError('too many 403 error responses'))
2025-01-28 18:21:12,612 - ERROR - HTTP error for https://news.mit.edu/topic/artificial-intelligence: 404 Client Error: Not Found for url: https://news.mit.edu/topic/artificial-intelligence
2025-01-28 18:21:23,932 - ERROR - HTTP error for https://openai.com/blog/: HTTPSConnectionPool(host='openai.com', port=443): Max retries exceeded with url: /blog/ (Caused by ResponseError('too many 403 error responses'))
2025-01-28 18:22:15,491 - ERROR - HTTP error for https://www.eleuther.ai/news/: 404 Client Error: Not Found for url: https://www.eleuther.ai/news/
2025-01-28 18:22:38,928 - ERROR - HTTP error for https://www.howtoforge.com/: HTTPSConnectionPool(host='www.howtoforge.com', port=443): Max retries exceeded with url: / (Caused by ResponseError('too many 403 error responses'))
2025-01-28 18:22:56,142 - ERROR - HTTP error for https://www.kdnuggets.com/: HTTPSConnectionPool(host='www.kdnuggets.com', port=443): Max retries exceeded with url: / (Caused by ResponseError('too many 403 error responses'))
2025-01-28 18:23:29,158 - ERROR - HTTP error for https://www.marktechpost.com/category/technology/ai-shorts/: HTTPSConnectionPool(host='www.marktechpost.com', port=443): Max retries exceeded with url: /category/technology/ai-shorts/ (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
